### ISSUE TITLE
`S3Path` does not support `'https'` S3 URL formats

### ISSUE THREAD

**Issue by surdoag** [drivendataorg/cloudpathlib#252] opened 2022-08-17 07:54 UTC
Trying to load S3 URLs in the HTTPS URL format is doesn't work. 

Tried subclassing, the `S3Path`. But that gives errors on for many methods & attributes like `_handle`, `parent` etc.

Is there a way to quickly handle this. 

Also please provide the support for `'https'` URL formats.

**Comment by pjbull** [comment] 2022-08-17 15:20
Closing as dupe of #152.

**Closed by pjbull** 2022-08-17 15:20 UTC

**Comment by pjbull** [comment] 2022-08-17 15:26
Also, as a note, #152 is the generic case.

If you have consistent and known url formats, you can likely write a small utility function that uses [urllib](https://docs.python.org/3/library/urllib.parse.html) to parse out the bucket and key and then make cloudpaths with the result: e.g., `CloudPath("s3://{parsed_bucket}/{parsed_key}`.

**Comment by surdoag** [comment] 2022-08-17 15:28
> Also, as a note, #152 is the generic case.
> 
> If you have consistent and known url formats, you can likely write a small utility function that uses [urllib](https://docs.python.org/3/library/urllib.parse.html) to parse out the bucket and key and then make cloudpaths with the result: e.g., `CloudPath("s3://{parsed_bucket}/{parsed_key}`.

That's what I've resorted to now. Thanks.
