### ISSUE TITLE
glob broken on Python 3.7

### ISSUE THREAD

**Issue by Quickblink** [drivendataorg/cloudpathlib#413] opened 2024-03-02 11:14 UTC
PR #202  introduced using `pathlib` internals for the `glob` implementation which make use of the `scandir` function as a `contextlib.contextmanager`. Apparently, `pathlib` used to work differently (expecting `scandir` to be an iterator directly) before 3.8 so `glob` essentially doesn’t work for older python versions. I would suggest dropping support as 3.7 has reached end-of-life status.

**Comment by pjbull** [comment] 2024-03-02 18:41
I think this is a dupe of https://github.com/drivendataorg/cloudpathlib/issues/210, not all 3.7. 

0.18.1 is already our last 3.7 supporting release:
https://github.com/drivendataorg/cloudpathlib/blob/master/HISTORY.md?plain=1#L13

**Closed by pjbull** 2024-03-02 18:41 UTC
