### ISSUE TITLE
S3Path inappropriately strips `/` characters when operating on valid S3 URLs

### ISSUE THREAD

**Issue by aryounce** [drivendataorg/cloudpathlib#351] opened 2023-07-21 06:39 UTC
Using this example bucket layout:

```
$ aws s3 ls s3://<my-s3-bucket>//test//
2023-07-21 06:23:49         15 test1.txt
2023-07-21 06:23:52         15 test2.txt
2023-07-21 06:23:54         15 test3.txt
```

`cloudpathlib.S3Path` fails to operate correctly when iterating over a list of paths generated by `S3Path.rglob()`. A test script to demonstrates the problem(s).

# Script
```
#!/usr/bin/env python3

from cloudpathlib import S3Path
from pprint import pprint

p = S3Path('s3://<my-s3-bucket>//test//')
pprint(p)

for o in p.rglob('*.txt'):
  pprint(o)
  # No file is written to `test_dir` (but the directory is created).
  o.download_to('test_dir')
  # This will throw an exception.
  pprint(o.stat())

```

# Output
```
$ ./slash-test.py
S3Path('s3://<my-s3-bucket>//test//')
S3Path('s3://<my-s3-bucket>/test/test1.txt')
Traceback (most recent call last):
  File "/home/ec2-user/project/.venv/lib/python3.10/site-packages/cloudpathlib/s3/s3path.py", line 61, in stat
    meta = self.client._get_metadata(self)
  File "/home/ec2-user/project/.venv/lib/python3.10/site-packages/cloudpathlib/s3/s3client.py", line 137, in _get_metadata
    data = self.s3.ObjectSummary(cloud_path.bucket, cloud_path.key).get(
  File "/home/ec2-user/project/.venv/lib/python3.10/site-packages/boto3/resources/factory.py", line 580, in do_action
    response = action(self, *args, **kwargs)
  File "/home/ec2-user/project/.venv/lib/python3.10/site-packages/boto3/resources/action.py", line 88, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "/home/ec2-user/project/.venv/lib/python3.10/site-packages/botocore/client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/ec2-user/project/.venv/lib/python3.10/site-packages/botocore/client.py", line 964, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.NoSuchKey: An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ec2-user/project/./slash-test.py", line 14, in <module>
    pprint(o.stat())
  File "/home/ec2-user/project/.venv/lib/python3.10/site-packages/cloudpathlib/s3/s3path.py", line 63, in stat
    raise NoStatError(
cloudpathlib.exceptions.NoStatError: No stats available for s3://<my-s3-bucket>/test/test1.txt; it may be a directory or not exist.
```

**Comment by aryounce** [comment] 2023-07-21 15:56
Following up, `S3Path.iterdir()` excludes the `/test` when attempting to list prefixes with the S3 URL `s3://<my-s3-bucket>/`. Depending on exactly how you express a URL for S3 the handling varies. Calling `iterdir()` on `s3://<my-s3-bucket>//test//` behaves as expected, with all of the objects being returned.

**Comment by pjbull** [comment] 2023-07-22 16:29
Thanks for filing the issue and for the details @aryounce.

The issue is that at any point in our code if we dispatch to `PurePosixPath`, the path is normalized, which replaces any repeated path separators with a single one. `PurePosixPath` is used as the implementation for most of the joining functionality and for `glob` because those implementations are complex with lots of edge cases, so it does not make sense for us to maintain separate implementations:

https://github.com/drivendataorg/cloudpathlib/blob/6b4afe9b553f7a25590f185c61fa73bf16c134a8/cloudpathlib/cloudpath.py#L648-L685

Additionally, resolving multiple path separators into a single separator is standard behavior for most file path systems and urls as well, for example:

```python
from pathlib import PurePosixPath
PurePosixPath("dir//file.txt")
#> PurePosixPath('dir/file.txt')

from urllib import parse
parse.urljoin("https://www.example.com/dir//", "page.html")
#> 'https://www.example.com/dir/page.html'
```

The reason that S3 supports multiple slashes in the object key is that it is an [object storage system, not a file system](https://www.redhat.com/en/topics/data-storage/file-block-object-storage). Basically, at an implementation level everything is in one huge directory so there is no concept of a path separator that defines a directory.

For `cloudpathlib` we make the assumption that you've structured your object storage to be like a file storage system, which gives you some convenience methods for manipulating objects _as if they were file system paths._

Unfortunately, I think you've encountered an edge case here where that assumption breaks down. I don't think there's a reasonable implementation where we can support multiple contiguous separators, even though this is a valid S3 object key. If your data looks like this, I'd recommend using `boto3` directly.

Closing for now, but will keep an eye on additional 👍 on this issue. If it is common (my hunch is probably not), we may look into some way of handling it.

**Closed by pjbull** 2023-07-22 16:29 UTC

**Comment by aryounce** [comment] 2023-07-22 18:44
First, I appreciate the response. What I feel needs to be highlighted is that S3 being an "object storage system, not a file system" is exactly why I created this issue. When I attempted to adopt `cloudpathlib` into a project my assumption was that the library was meant to handle the feature mismatch between S3 and the local file system. At first glance the projects goal seems to be to make it easier to work with objects remotely and locally. What I'm understanding from your response is that it's actually meant to impose (intentionally, and in a good way) *file system semantics on S3*.

I'm not sure that restricting a S3 client to the POSIX file system requirements is the right approach, but I respect that this project's goals don't align with my own. Also, `cloudpathlib` isn't *just* a S3 client so perhaps the subset of things it can do is better for the support of GCP and Azure.

Should the project's position be reconsidered I think that having a clean separation between cloud object storage and a local file system, with the library gracefully handling the differences, would be valuable. Thanks again.

**Comment by pjbull** [comment] 2023-07-22 19:43
Yeah, we'd love to cover this case, but the concern is more pragmatic than conceptual. To me, the fixes look like either (1) re-implement all the joining logic from `PurePosixPath` or (2) do bookkeeping to track where there are multiple separators and re-insert them as necessary. 

That said, now I'm thinking there may be an sub-case worth considering. Are you consistently using `//` as a separator everywhere? Customizing the separator character is feasible, but handling a varying number of separators probably is not.

In this case, you could try monkey-patching `PurePosixPath` to see if it helps (for example add `PurePosixPath.pathmod.sep = "//"`). If that works for your case, we would consider a separate issue to make the separator user-specified.

Second, if you just need `rglob` and not the joining methods, you could potentially use `Client._list_dir` and to the filtering yourself. It's not a public API, so be warned, but I do think it is pretty stable at this point.

For example:

```python
import fnmatch
from cloudpathlib import CloudPath

cp = CloudPath("s3://bucket/dir")
all_files = (p.key for p in cp.client._list_dir(cp, recursive=True))
text_files = fnmatch.filter(all_files, "*.txt")
```

**Comment by aryounce** [comment] 2023-07-22 20:20
In my case I'm dealing with S3 buckets that I don't control. Sometimes the object keys have compound `/` characters, especially at the beginning.

**Comment by pjbull** [comment] 2023-07-22 20:28
Gotcha, unfortunately for the reasons above supporting that scenario generically is out of scope.

Hopefully at least the `rglob` workaround above could be useful to you since I believe that will let you list and download files like in the script.

**Comment by gordonwade** [comment] 2023-11-28 21:40
Hi all - I just wanted to let you know that I am also in @aryounce's position. I'm looking for a library that will help me work with blobs in cloud storage including those that are externally controlled (sometimes having interesting conventions such as the double slash `//`). Last year, I forked and updated a different library for this, but there have been substantial changes and I'm not sure it's worth reimplementing. At any rate, I'll be tracking this issue in case the position is reconsidered.
